# Generated by Django 2.0.5 on 2018-06-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='rid',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access',
            name='uid',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='rid',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='uid',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
