# Generated by Django 2.0.5 on 2018-06-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority_backend', '0002_auto_20180605_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='rid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='access',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='rid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
