# Generated by Django 2.0.5 on 2018-06-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authority_backend', '0003_auto_20180605_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ownership',
            new_name='shoppingcart',
        ),
    ]
