# Generated by Django 2.0.5 on 2018-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority_backend', '0004_auto_20180605_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('fid', models.IntegerField()),
            ],
        ),
    ]
