# Generated by Django 2.0.2 on 2018-06-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority_backend', '0005_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='rid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='access',
            name='uid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='rid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
